apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/kargo
patches:
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kargo
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: kargo.k8s.badgerops.io
      - op: add
        path: /spec/rules/0/backendRefs/0/group
        value: ""
      - op: add
        path: /spec/rules/0/backendRefs/0/kind
        value: Service
      - op: add
        path: /spec/rules/0/backendRefs/0/weight
        value: 1
