apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
helmCharts:
  - name: podinfo
    repo: oci://ghcr.io/stefanprodan/charts
    version: 6.11.2
    releaseName: podinfo
    namespace: podinfo
    valuesFile: values.yaml
