replicaCount: 2

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

serviceMonitor:
  enabled: true

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 80
  memory: 100Mi
