apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: podinfo
  namespace: podinfo
spec:
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
    scaleDown: argo-rollouts
  strategy:
    canary:
      analysis:
        templates:
          - templateName: podinfo-error-rate
        startingStep: 1
      steps:
        - setWeight: 10
        - pause: {duration: 15s}
        - setWeight: 20
        - pause: {duration: 15s}
        - setWeight: 30
        - pause: {duration: 15s}
        - setWeight: 40
        - pause: {duration: 15s}
        - setWeight: 50
        - pause: {duration: 15s}
        - setWeight: 60
        - pause: {duration: 15s}
        - setWeight: 70
        - pause: {duration: 15s}
        - setWeight: 80
        - pause: {duration: 15s}
        - setWeight: 90
        - pause: {duration: 15s}
