apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: git-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
  data:
    - secretKey: repoURL
      remoteRef:
        key: kargo-git-repo-url
    - secretKey: username
      remoteRef:
        key: kargo-git-username
    - secretKey: password
      remoteRef:
        key: kargo-git-token
