apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: badgerops
  namespace: demo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: podinfo
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/theopsbadger/badgerops.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: ./repo/argocd/overlays/badgerops/podinfo
            images:
              - image: ghcr.io/stefanprodan/podinfo
                tag: ${{ imageFrom("ghcr.io/stefanprodan/podinfo").Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "chore: promote podinfo ${{ imageFrom(\"ghcr.io/stefanprodan/podinfo\").Tag }}"
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
