apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teleport-join-token
  namespace: teleport
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: teleport-kube-agent-join-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: auth-token
      remoteRef:
        key: teleport-join-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
