apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport
resources:
  - namespace.yaml
  - externalsecret.yaml
helmCharts:
  - name: teleport-kube-agent
    repo: https://charts.releases.teleport.dev
    version: 17.4.4
    releaseName: teleport-kube-agent
    namespace: teleport
    valuesFile: values.yaml
