apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-secrets
  namespace: kargo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: kargo-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ADMIN_ACCOUNT_PASSWORD_HASH
      remoteRef:
        key: kargo-admin-password-hash
    - secretKey: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
      remoteRef:
        key: kargo-admin-token-signing-key
    - secretKey: DEX_GITHUB_CLIENT_ID
      remoteRef:
        key: kargo-dex-github-client-id
    - secretKey: DEX_GITHUB_CLIENT_SECRET
      remoteRef:
        key: kargo-dex-github-client-secret
