apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/online-boutique

images:
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.5
  - name: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newTag: v0.10.5

patches:
  - target:
      group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: online-boutique
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: shop.k8s.badgerops.io
