apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/bookinfo
patches:
  - target:
      kind: HTTPRoute
      name: bookinfo
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: bookinfo.k8s.badgerops.io
