labels:
  istio: eastwestgateway
  app: istio-eastwestgateway
  topology.istio.io/network: network1   # patched to network2 in cluster2 overlay

env:
  ISTIO_META_ROUTER_MODE: "sni-dnat"
  ISTIO_META_REQUESTED_NETWORK_VIEW: "network1"   # patched to network2 in cluster2 overlay

service:
  type: LoadBalancer
  ports:
    - name: status-port
      port: 15021
      targetPort: 15021
    - name: tls
      port: 15443
      targetPort: 15443
    - name: tls-istiod
      port: 15012
      targetPort: 15012
    - name: tls-webhook
      port: 15017
      targetPort: 15017

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
