apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/istio-gateway
  - authz-policy.yaml
patches:
  - target:
      kind: Service
      name: istio-gateway-istio
    patch: |
      - op: replace
        path: /spec/externalTrafficPolicy
        value: Local
