apiVersion: v1
kind: Service
metadata:
  name: istio-gateway-istio
  namespace: istio-gateway
spec:
  loadBalancerSourceRanges:
    - 8.29.230.139/32
    - 8.29.230.140/32
    - 8.29.231.139/32
    - 8.29.231.140/32
    # GitHub webhook IPs (https://api.github.com/meta)
    - 192.30.252.0/22
    - 185.199.108.0/22
    - 140.82.112.0/20
    - 143.55.64.0/20
