configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-helm
    admin.enabled: "false"
    url: http://34.173.79.193
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23lijPj0PQJnlIx2tf
            clientSecret: $dex.github.clientSecret
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, theopsbadger, role:admin
repoServer:
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
server: {}
