configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-helm
    admin.enabled: "false"
    url: https://argocd.k8s.badgerops.io
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23lijPj0PQJnlIx2tf
            clientSecret: $dex.github.clientSecret
  rbac:
    policy.default: role:''
    policy.csv: |
      g, theopsbadger, role:admin
      # Add additional GitHub users below:
      # g, <github-username>, role:admin
      # g, <github-username>, role:readonly
repoServer:
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
server: {}
