configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: --enable-helm
    admin.enabled: "false"
    url: https://argocd.k8s.badgerops.io
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23lijPj0PQJnlIx2tf
            clientSecret: $dex.github.clientSecret
  rbac:
    policy.default: role:''
    scopes: '[preferred_username, groups]'
    policy.csv: |
      g, theopsbadger, role:admin
      # Add additional GitHub users below:
      # g, <github-username>, role:admin
      # g, <github-username>, role:readonly
repoServer:
  livenessProbe:
    initialDelaySeconds: 30
  readinessProbe:
    initialDelaySeconds: 30
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

applicationSet:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 128Mi

controller:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

server:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
